### ISSUE TITLE
微信登录，语音对话播放音乐提示登录失效。

### ISSUE THREAD

**Issue by 6d616c66** [TencentDingdang/dmsdk#1]
微信登录，语音对话播放音乐提示登录失效。QQ登录没有问题，你们这边知道什么问题吗？

**Comment by perqin** [comment]
请问现在使用最新版还有问题吗？

**Comment by 6d616c66** [comment]
现在OK了，配置的设备端环境是测试环境的，app使用的是正式环境导致的。

**Comment by perqin** [comment]
好的，有其他问题欢迎提出issue。
