### ISSUE TITLE
华为P30 Pro EMUI 9.1.0 微信未登录时，不会回调onSuccess()和onError(int code)

### ISSUE THREAD

**Issue by afunx** [TencentDingdang/dmsdk#2]
环境：
项目中使用的是v2.1.3。
为了验证该问题时候，我尝试过v2.1.4和v2.2.0，但该问题还是存在
其中，v2.2.0需要项目整体迁移到AndroidX。

复现方法：
1. 微信未登录
2. LoginProxy.getInstance().tvsLogin(ELoginPlatform.WX, loginActivity, loginActivity);
其中，loginActivity已实现TVSCallback接口
3. 其他手机，微信成功登录后，会回调loginActivity的onSuccess()或onError(int code)。
但是，P30 Pro EMUI 9.1.0并不会调用onSuccess()，也不会调用onError(int code)。

补充说明：
如果微信已经登录，即使P30 Pro EMUI 9.1.0也不会出现这个问题。一定要微信未登录时，调用tvsLogin后，用户手动登录微信，才会出现这种情况。

**Comment by perqin** [comment]
我这里使用P30 Pro EMUI 9.1.0，DM SDK 2.2.1，微信未登录后拉起登录后能够授权，并且回到DM SDK demo后能够收到onSuccess回调，使用的微信登录SDK是`com.tencent.mm.opensdk:wechat-sdk-android-with-mta:5.4.0`，麻烦更新到最新版2.2.1后再尝试一下。

**Comment by afunx** [comment]
好的。但v2.2.1需要项目整体迁移到AndroidX。目前，我司android暂时不会切换到AndroidX。
交互已经提供了处理方案。

这个问题先关了。
