### ISSUE TITLE
iOS 13 UIWebView 的问题

### ISSUE THREAD

**Issue by heronlyj** [TencentDingdang/dmsdk#3]
![image](https://user-images.githubusercontent.com/5340305/67274203-8c9eef80-f4f2-11e9-92a4-bda5f66649fe.png)

请问 dmSdk  里使用到的 UIWebView 问题什么时候能更新一个版本？还是说自己更新 TencentOpenSDK.framework 和 微信 Sdk ? TVS 相关包内不需要更新吗？

**Comment by mmm2006** [comment]
同样的问题，请帮忙回复下。谢谢

**Comment by perqin** [comment]
感谢反馈，我们会在后续版本处理该问题。DM SDK依赖了AFNetworking，而该库目前会依赖UIWebView。

**Comment by perqin** [comment]
根据AFNetworking的[这个issue](https://github.com/AFNetworking/AFNetworking/issues/4428)，只需要使用subspec方式避免用到UIKit即可。DM SDK仅使用到了Reachability，demo中已经进行了相应的修改，参考demo修改Podfile文件并更新依赖即可。

**Comment by mmm2006** [comment]
不能全部解决问题：编译会找不到：<AFNetworking/AFHTTPSessionManager.h>，编译不过。

**Comment by perqin** [comment]
DM SDK中未使用`<AFNetworking/AFHTTPSessionManager.h>`，如果您的项目中使用到了Reachability之外的其他subspec，请在Podfile中增加对应的subspec。以缺失`<AFNetworking/AFHTTPSessionManager.h>`为例，Podfile需要从：

```
pod 'AFNetworking', '~>3.0', :subspecs => ['Reachability']
```

改为：

```
pod 'AFNetworking', '~>3.0', :subspecs => ['Reachability', 'NSURLSession']
```

**Comment by mmm2006** [comment]
抱歉，可能我写错了。应该是缺少：AFNetworking/AFNetworking.h， 这个是在哪个subspec里面呢？谢谢

**Comment by perqin** [comment]
`AFNetworking/AFNetworking.h`是汇总的头文件，使用subspec方式时无法使用这个头文件，需要根据代码里用到的具体类修改为`AFNetworking/****.h`，这个需要您看一下使用了这个头文件的地方具体用到了哪个subspec的功能。
