### ISSUE TITLE
Xcode10.1编译报错，兼容问题

### ISSUE THREAD

**Issue by iOSDeveloperOfChina** [TencentDingdang/dmsdk#4]
Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      l001 in TVSCore(TVSAppUtil.o)
      l014 in TVSWeb(TVSWeb.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
背景：项目中有些SDK无法在xcode11上运行，暂时使用Xcdoe10.1。
项目在Xcode10.1上编译报错，信息如上，感觉像xcode11使用@available关键字问题，希望使用[UIDevice currentDevice].systemVersion.floatValue 适配下，谢谢！

**Comment by mmm2006** [comment]
xcode 10.2.1上编译不过demo，目前项目不能升级xcode，如何解决，请帮忙。谢谢

**Comment by perqin** [comment]
DM SDK的iOS 2.2.1版本修复了该问题，请使用该版本。DM SDK支持的Xcode版本是10.1及以上。
